[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'


[tool.check-manifest]
ignore = [
    "src/geovista/_version.py",
]


[tool.codespell]
skip = ".git,*.ipynb"


[tool.ruff]
ignore = [
    "D105",  # pydocstyle: undocumented-magic-method
]
extend-exclude = [
    "docs",
]
line-length = 88
select = [
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "I",   # isort
    "E",   # pycodestyle
    "W",
    "D",   # pydocstyle
    "F",   # pyflakes
    "UP",  # pyupgrade
]
target-version = "py311"


[tool.ruff.isort]
force-sort-within-sections = true
known-first-party = ["geovista"]


[tool.ruff.mccabe]
max-complexity = 22


[tool.ruff.pydocstyle]
convention = "numpy"
